#!/bin/sh
#
# reload-cincy
# pre-commit git hook
# 
# Created by Alexander Burdiss 6/20/22
# Version 1.0.0
# 

# ./scripts/bundlejs.sh
# git add ./bundle.js

./scripts/generateSitemap.sh
git add ./sitemap.xml

